---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: online-boutique-alerts
  namespace: monitoring
  labels:
    app: online-boutique
    release: prometheus
spec:
  groups:
  - name: online-boutique.sre.rules
    interval: 30s
    rules:
    
    # High Error Rate Alert
    - alert: HighErrorRate
      expr: |
        (
          sum(rate(http_requests_total{job="online-boutique",status=~"5.."}[5m]))
          /
          sum(rate(http_requests_total{job="online-boutique"}[5m]))
        ) > 0.05
      for: 5m
      labels:
        severity: critical
        component: application
        team: sre
      annotations:
        summary: "Alta taxa de erros detectada ({{ $value | humanizePercentage }})"
        description: "O serviço {{ $labels.service }} está apresentando taxa de erro acima de 5% nos últimos 5 minutos."
        runbook_url: "https://runbooks.example.com/high-error-rate"
    
    # High Latency Alert
    - alert: HighLatency
      expr: |
        histogram_quantile(0.95,
          sum(rate(http_request_duration_seconds_bucket{job="online-boutique"}[5m])) by (le, service)
        ) > 1
      for: 5m
      labels:
        severity: warning
        component: performance
        team: sre
      annotations:
        summary: "Alta latência detectada no serviço {{ $labels.service }}"
        description: "P95 de latência está em {{ $value | humanizeDuration }} (threshold: 1s)"
        runbook_url: "https://runbooks.example.com/high-latency"
    
    # Pod Crash Loop
    - alert: PodCrashLooping
      expr: |
        rate(kube_pod_container_status_restarts_total{namespace="online-boutique"}[15m]) > 0
      for: 5m
      labels:
        severity: critical
        component: kubernetes
        team: sre
      annotations:
        summary: "Pod {{ $labels.pod }} está em crash loop"
        description: "O pod {{ $labels.pod }} no namespace {{ $labels.namespace }} está reiniciando continuamente."
        runbook_url: "https://runbooks.example.com/pod-crash-loop"
    
    # High CPU Usage
    - alert: HighCPUUsage
      expr: |
        sum(rate(container_cpu_usage_seconds_total{namespace="online-boutique",container!=""}[5m])) by (pod)
        /
        sum(kube_pod_container_resource_limits{namespace="online-boutique",resource="cpu"}) by (pod)
        > 0.90
      for: 10m
      labels:
        severity: warning
        component: resources
        team: sre
      annotations:
        summary: "Alto uso de CPU no pod {{ $labels.pod }}"
        description: "O pod {{ $labels.pod }} está usando {{ $value | humanizePercentage }} do limite de CPU."
        runbook_url: "https://runbooks.example.com/high-cpu"
    
    # High Memory Usage
    - alert: HighMemoryUsage
      expr: |
        sum(container_memory_working_set_bytes{namespace="online-boutique",container!=""}) by (pod)
        /
        sum(kube_pod_container_resource_limits{namespace="online-boutique",resource="memory"}) by (pod)
        > 0.90
      for: 10m
      labels:
        severity: warning
        component: resources
        team: sre
      annotations:
        summary: "Alto uso de memória no pod {{ $labels.pod }}"
        description: "O pod {{ $labels.pod }} está usando {{ $value | humanizePercentage }} do limite de memória."
        runbook_url: "https://runbooks.example.com/high-memory"
    
    # Pod Not Ready
    - alert: PodNotReady
      expr: |
        sum by (namespace, pod) (
          kube_pod_status_phase{namespace="online-boutique",phase!~"Running|Succeeded"}
        ) > 0
      for: 5m
      labels:
        severity: critical
        component: kubernetes
        team: sre
      annotations:
        summary: "Pod {{ $labels.pod }} não está Ready"
        description: "O pod {{ $labels.pod }} no namespace {{ $labels.namespace }} não está em estado Running há mais de 5 minutos."
        runbook_url: "https://runbooks.example.com/pod-not-ready"
    
    # HPA at Max Capacity
    - alert: HPAMaxedOut
      expr: |
        kube_horizontalpodautoscaler_status_current_replicas{namespace="online-boutique"}
        /
        kube_horizontalpodautoscaler_spec_max_replicas{namespace="online-boutique"}
        >= 1
      for: 15m
      labels:
        severity: warning
        component: autoscaling
        team: sre
      annotations:
        summary: "HPA {{ $labels.horizontalpodautoscaler }} atingiu capacidade máxima"
        description: "O HPA está no máximo de réplicas há mais de 15 minutos. Considere aumentar o limite."
        runbook_url: "https://runbooks.example.com/hpa-maxed"
    
    # Service Down
    - alert: ServiceDown
      expr: |
        up{job="online-boutique"} == 0
      for: 2m
      labels:
        severity: critical
        component: availability
        team: sre
      annotations:
        summary: "Serviço {{ $labels.service }} está down"
        description: "O serviço {{ $labels.service }} não está respondendo há mais de 2 minutos."
        runbook_url: "https://runbooks.example.com/service-down"
    
    # Low Request Rate (possible issue)
    - alert: LowRequestRate
      expr: |
        sum(rate(http_requests_total{job="online-boutique"}[5m])) < 1
      for: 10m
      labels:
        severity: warning
        component: traffic
        team: sre
      annotations:
        summary: "Taxa de requisições muito baixa"
        description: "A aplicação está recebendo menos de 1 req/s nos últimos 10 minutos. Possível problema."
        runbook_url: "https://runbooks.example.com/low-traffic"

  - name: online-boutique.slo.rules
    interval: 30s
    rules:
    
    # SLI: Availability (Success Rate)
    - record: sli:availability:ratio
      expr: |
        sum(rate(http_requests_total{job="online-boutique",status!~"5.."}[5m]))
        /
        sum(rate(http_requests_total{job="online-boutique"}[5m]))
    
    # SLI: Latency (P95 < 1s)
    - record: sli:latency:p95
      expr: |
        histogram_quantile(0.95,
          sum(rate(http_request_duration_seconds_bucket{job="online-boutique"}[5m])) by (le)
        )
    
    # SLI: Latency (P99 < 2s)
    - record: sli:latency:p99
      expr: |
        histogram_quantile(0.99,
          sum(rate(http_request_duration_seconds_bucket{job="online-boutique"}[5m])) by (le)
        )
    
    # SLO: 99.9% Availability
    - alert: SLOAvailabilityBreach
      expr: |
        sli:availability:ratio < 0.999
      for: 5m
      labels:
        severity: critical
        component: slo
        team: sre
      annotations:
        summary: "SLO de disponibilidade violado"
        description: "Disponibilidade atual: {{ $value | humanizePercentage }} (SLO: 99.9%)"
        runbook_url: "https://runbooks.example.com/slo-breach"
    
    # SLO: P95 Latency < 1s
    - alert: SLOLatencyBreach
      expr: |
        sli:latency:p95 > 1
      for: 5m
      labels:
        severity: warning
        component: slo
        team: sre
      annotations:
        summary: "SLO de latência P95 violado"
        description: "Latência P95 atual: {{ $value | humanizeDuration }} (SLO: 1s)"
        runbook_url: "https://runbooks.example.com/slo-latency-breach"

